#! /bin/sh

$HOME/.config/polybar/launch.sh
feh --bg-fill --randomize ~/wallpaper/
xscreensaver -no-splash &
sxhkd &

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding    30


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



xsetroot -cursor_name left_ptr

setxkbmap -layout us,ru -option grp:win_space_toggle &

# Compton
if [ -x "$(command -v picom)" ]
then
    killall picom;picom -b --dbus
elif [ -x "$(command -v compton)" ]
then
    killall compton;compton --config ~/.config/compton/compton.conf -b --dbus
fi
